#!/usr/bin/env bash
# Generated by @burson.kendrick/claude-gh-task-manager install — do not edit.
PKG="$(cd "$(dirname "$0")/../.." && pwd)/node_modules/@burson.kendrick/claude-gh-task-manager"
exec bash "$PKG/hooks/task-tracker.sh"
