// @story #1836
export function observation(context, callId = 'call-1') {
  return {
    schemaVersion: 'aitm.graphql-usage.observation/v1',
    callId,
    logicalOperationId: callId,
    startedAt: '2026-09-28T00:00:00.000Z',
    endedAt: '2026-09-28T00:00:00.010Z',
    durationMs: 10,
    worktreeId: context.worktreeId,
    sessionId: context.sessionId,
    sessionSource: context.sessionSource,
    enrollmentId: context.enrollmentId,
    commonRootId: context.commonRootId,
    processId: process.pid,
    repository: 'example/test',
    issueNumber: 1836,
    draftId: null,
    lifecycleState: 'develop',
    stateSource: 'local',
    contextScope: 'single-issue',
    collectorLaunchRoute: 'measurement-launcher',
    originatingLaunchRoute: null,
    observationKind: 'http-attempt',
    dispatchStatus: 'sent',
    pageIndex: null,
    operation: 'GetIssue',
    queryFingerprint: null,
    kind: 'query',
    outcome: 'success',
    httpStatus: 200,
    processExitCode: null,
    errorClass: null,
    pointCost: 1,
    costSource: 'same-response-rate-limit',
    costUnknownReason: null,
    costCoverage: 'complete-observation',
    hiddenRequestCount: 0,
    costBasis: 'instrumented-request',
    augmentationVersion: null,
    collectorVersion: 'v1',
    endpointHost: 'api.github.com',
    budgetScopeId: null,
    rateLimit: null,
    rateLimitUnavailableReason: 'not-returned',
  };
}
