// Word counter — extracted from tally-chat-words.mjs for reuse.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';

export function projectKey() {
  const dir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
  return dir.replace(/\//g, '-');
}

export function sessionDir() {
  return path.join(os.homedir(), '.claude', 'projects', projectKey());
}

export function jsonlPath(sid) {
  return path.join(sessionDir(), `${sid}.jsonl`);
}

export function markerPathFor(sid) {
  return path.join(sessionDir(), `${sid}.word-marker`);
}

export function currentSessionId() {
  try {
    const dir = sessionDir();
    const files = readdirSync(dir).filter((f) => f.endsWith('.jsonl'));
    if (!files.length) return null;
    return files
      .map((f) => ({ f, mtime: statSync(path.join(dir, f)).mtimeMs }))
      .sort((a, b) => b.mtime - a.mtime)[0]
      .f.replace('.jsonl', '');
  } catch {
    return null;
  }
}

export function loadMarker(markerPath) {
  if (!existsSync(markerPath)) return { line: 0, words: 0, task: null };
  try {
    const parsed = JSON.parse(readFileSync(markerPath, 'utf8'));
    return { line: 0, words: 0, task: null, ...parsed };
  } catch {
    return { line: 0, words: 0, task: null };
  }
}

export function saveMarker(markerPath, line, words, task = null) {
  writeFileSync(
    markerPath,
    JSON.stringify({ line, words, task, ts: new Date().toISOString() }, null, 2),
    'utf8'
  );
}

// Prefixes/markers that indicate injected (non-reader-visible) text.
// These arrive as user-typed content in the JSONL but are never rendered in
// the chat window — they're system-reminders, slash-command scaffolding,
// skill bodies, local command stdout, etc. Counting them inflates the
// "reader effort" measurement.
const INJECTION_PREFIXES = [
  '<system-reminder>',
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<user-memory>',
  '<bash-input>',
  '<bash-stdout>',
  '<bash-stderr>',
  'Caveat: The messages below were generated by the user while running local commands',
  'Base directory for this skill:',
  'This session is being continued from a previous conversation',
];

export function isInjection(text) {
  if (typeof text !== 'string') return false;
  const t = text.trimStart();
  if (!t) return true; // empty strings don't count as reader effort
  for (const p of INJECTION_PREFIXES) {
    if (t.startsWith(p)) return true;
  }
  return false;
}

function wordCount(text) {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

export function countWords(filePath, fromLine = 0) {
  if (!existsSync(filePath)) return { count: 0, totalLines: 0 };
  const lines = readFileSync(filePath, 'utf8').split('\n').filter(Boolean);
  let count = 0;
  for (let i = fromLine; i < lines.length; i++) {
    let obj;
    try {
      obj = JSON.parse(lines[i]);
    } catch {
      continue;
    }
    if (obj.type !== 'user' && obj.type !== 'assistant') continue;
    // Skip meta/sidechain entries — tool output piped as user turns, hook injections, etc.
    if (obj.isMeta || obj.isSidechain) continue;
    const content = obj.message?.content;
    if (!content) continue;
    if (typeof content === 'string') {
      if (isInjection(content)) continue;
      count += wordCount(content);
    } else if (Array.isArray(content)) {
      for (const block of content) {
        if (block?.type !== 'text' || typeof block.text !== 'string') continue;
        if (isInjection(block.text)) continue;
        count += wordCount(block.text);
      }
    }
  }
  return { count, totalLines: lines.length };
}
