// Word counter — extracted from tally-chat-words.mjs for reuse.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { readdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { homedir } from 'node:os';

export function projectKey() {
  const dir = projectDir();
  // Flatten path separators (POSIX `/`, Windows `\`) and the Windows drive colon.
  return dir.replace(/[\\/:]/g, '-');
}

export function projectDir() {
  return process.env.AI_TASK_MANAGER_PROJECT_DIR || process.env.CLAUDE_PROJECT_DIR || process.cwd();
}

export function aiAppName() {
  // TODO(#203): route through provider registry (detectProvider + sessionIdEnvKeys)
  const explicit = process.env.AI_TASK_MANAGER_APP_NAME?.trim().toLowerCase();
  if (explicit === 'claude' || explicit === 'codex') return explicit;
  if (process.env.CODEX_SESSION_ID || process.env.CODEX_HOME) return 'codex';
  return 'claude';
}

export function appStateDir() {
  // TODO(#203): route through provider registry (stateDir capability)
  return path.join(projectDir(), '.ai-task-manager', aiAppName());
}

export function transcriptDir() {
  // TODO(#203): route through provider registry (transcriptLocator capability)
  if (process.env.AI_TASK_MANAGER_TRANSCRIPT_DIR) return process.env.AI_TASK_MANAGER_TRANSCRIPT_DIR;
  const local = path.join(appStateDir(), 'session-transcripts');
  if (existsSync(local)) return local;
  // Fall back to Claude Code's native per-project transcript directory when the
  // local session-transcripts directory hasn't been created (e.g. pre-existing
  // install). Claude stores session JSONL at ~/.claude/projects/<encoded-path>/.
  if (aiAppName() === 'claude') {
    const claudeDir = path.join(homedir(), '.claude', 'projects', projectKey());
    if (existsSync(claudeDir)) return claudeDir;
  }
  return local;
}

export function markerDir() {
  return path.join(appStateDir(), 'session-tracking');
}

export function jsonlPath(sid) {
  return path.join(transcriptDir(), `${sid}.jsonl`);
}

export function markerPathFor(sid) {
  return path.join(markerDir(), `${sid}.json`);
}

export function ensureSessionTracking(sid) {
  const trackingPath = markerPathFor(sid);
  if (existsSync(trackingPath)) return;
  mkdirSync(path.dirname(trackingPath), { recursive: true });
  writeFileSync(
    trackingPath,
    JSON.stringify(
      {
        sessionId: sid,
        startedAt: new Date().toISOString(),
        wordCount: { line: 0, words: 0, task: null, ts: null },
      },
      null,
      2
    ),
    'utf8'
  );
}

export function currentSessionId() {
  // Prefer the authoritative session id exported via env. The
  // mtime-sort fallback is fragile (stale .jsonl touched by an editor or
  // indexer can outrank the live session) and only runs when the env var
  // is unset or empty.
  // TODO(#203): route through provider registry (sessionIdEnvKeys capability)
  for (const key of ['AI_TASK_MANAGER_SESSION_ID', 'CODEX_SESSION_ID', 'CLAUDE_SESSION_ID']) {
    const envSid = process.env[key];
    if (typeof envSid === 'string' && envSid.length > 0) return envSid;
  }
  try {
    const dir = transcriptDir();
    const files = readdirSync(dir).filter((f) => f.endsWith('.jsonl'));
    if (!files.length) return null;
    return files
      .map((f) => ({ f, mtime: statSync(path.join(dir, f)).mtimeMs }))
      .sort((a, b) => b.mtime - a.mtime)[0]
      .f.replace('.jsonl', '');
  } catch {
    return null;
  }
}

export function loadMarker(markerPath) {
  if (!existsSync(markerPath)) return { line: 0, words: 0, task: null };
  try {
    const { wordCount = {} } = JSON.parse(readFileSync(markerPath, 'utf8'));
    return { line: 0, words: 0, task: null, ...wordCount };
  } catch {
    return { line: 0, words: 0, task: null };
  }
}

export function saveMarker(markerPath, line, words, task = null) {
  mkdirSync(path.dirname(markerPath), { recursive: true });
  let existing = {};
  try {
    if (existsSync(markerPath)) existing = JSON.parse(readFileSync(markerPath, 'utf8'));
  } catch {}
  writeFileSync(
    markerPath,
    JSON.stringify(
      { ...existing, wordCount: { line, words, task, ts: new Date().toISOString() } },
      null,
      2
    ),
    'utf8'
  );
}

// Prefixes/markers that indicate injected (non-reader-visible) text.
// These arrive as user-typed content in the JSONL but are never rendered in
// the chat window — they're system-reminders, slash-command scaffolding,
// skill bodies, local command stdout, etc. Counting them inflates the
// "reader effort" measurement.
const INJECTION_PREFIXES = [
  '<system-reminder>',
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<user-memory>',
  '<bash-input>',
  '<bash-stdout>',
  '<bash-stderr>',
  'Caveat: The messages below were generated by the user while running local commands',
  'Base directory for this skill:',
  'This session is being continued from a previous conversation',
];

export function isInjection(text) {
  if (typeof text !== 'string') return false;
  const t = text.trimStart();
  if (!t) return true; // empty strings don't count as reader effort
  for (const p of INJECTION_PREFIXES) {
    if (t.startsWith(p)) return true;
  }
  return false;
}

function wordCount(text) {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

export function countWords(filePath, fromLine = 0) {
  if (!existsSync(filePath)) return { count: 0, totalLines: 0 };
  const lines = readFileSync(filePath, 'utf8').split('\n').filter(Boolean);
  let count = 0;
  for (let i = fromLine; i < lines.length; i++) {
    let obj;
    try {
      obj = JSON.parse(lines[i]);
    } catch {
      continue;
    }
    if (obj.type !== 'user' && obj.type !== 'assistant') continue;
    // Skip meta/sidechain entries — tool output piped as user turns, hook injections, etc.
    if (obj.isMeta || obj.isSidechain) continue;
    const content = obj.message?.content;
    if (!content) continue;
    if (typeof content === 'string') {
      if (isInjection(content)) continue;
      count += wordCount(content);
    } else if (Array.isArray(content)) {
      for (const block of content) {
        if (block?.type !== 'text' || typeof block.text !== 'string') continue;
        if (isInjection(block.text)) continue;
        count += wordCount(block.text);
      }
    }
  }
  return { count, totalLines: lines.length };
}
