// @story #1266

const command = (definition) => Object.freeze(definition);

export const COMMANDS = Object.freeze({
  start: command({
    purpose:
      'Interactively or non-interactively initialize one protocol and publish durable author/reviewer handoffs.',
    caller: 'The human coordinator or automation preparing a new author/reviewer exchange.',
    lifecycleStates: ['absent'],
    mutationBoundary:
      'Delegates lifecycle creation to init, then publishes startup metadata and handoffs inside the ignored protocol directory; it does not launch agents or mutate Git/task state.',
    prerequisites: [
      'Run in the Git worktree containing the authoritative committed artifact.',
      'Interactive use requires a terminal; automation supplies artifact, author, and reviewer flags.',
      'Author and reviewer identities must be distinct and the runtime directory must satisfy init containment and ignore rules.',
    ],
    usage:
      'npx aitm co-review start [--artifact <repo-path> --owner <author-identity> --reviewer <reviewer-identity>] [--dir <ignored-path>] [--max-turns <N>] [--wait-cycles <N>] [--wait-interval <seconds>]',
    arguments: [
      '(no flags)                     Interactive wizard with review before confirmation.',
      '--artifact <repo-path>         Authoritative tracked artifact.',
      '--owner <author-identity>      Identity assigned the existing protocol owner role.',
      '--reviewer <reviewer-identity> Distinct external reviewer identity.',
      '--dir <ignored-path>           Optional runtime directory; default is unique below .tmp/co-review/.',
      '--max-turns <N>                Positive reviewer-handoff maximum; default 10.',
      '--wait-cycles <N>              Positive observed waits per episode; default 20.',
      '--wait-interval <seconds>      Integer from 1 through 60; default 60.',
    ],
    effects: [
      'Shows every resolved interactive value and requires confirmation before mutation; cancellation exits successfully with no state changed.',
      'Calls the existing initialization machinery and preserves aitm.co-review/v1 as lifecycle authority.',
      'Publishes author-handoff.md, reviewer-handoff.md, and start-manifest.json only inside the ignored protocol directory.',
      'Prints only two thin labeled agent prompts after all startup files pass exact-byte and hash verification.',
    ],
    validations: [
      'Repository/worktree, tracked artifact, ignored contained runtime, distinct identities, numeric limits, protocol compatibility, generated bytes, and manifest hashes.',
      'A complete non-interactive invocation bypasses the wizard; missing required flags without a terminal are invalid usage.',
    ],
    output:
      'After interactive collection, prints AUTHOR PROMPT and REVIEWER PROMPT blocks pointing to absolute handoff paths; it does not launch agents.',
    exits:
      '0=start/help/cancellation; 1=runtime, protocol, publication, retry, or content conflict; 2=invalid or incomplete usage.',
    transition: 'Absent -> active owner round 1 through the same initializer as init.',
    idempotency:
      'An exact retry with the explicit resolved --dir adds no event and rewrites no identical file; validated missing startup material may be reconstructed, while every conflict refuses.',
    examples: [
      'npx aitm co-review start',
      'npx aitm co-review start --artifact docs/design.md --owner author-agent --reviewer reviewer-agent',
      'npx aitm co-review start --artifact docs/design.md --owner author-agent --reviewer reviewer-agent --dir .tmp/co-review/design-fixed --max-turns 10 --wait-cycles 20 --wait-interval 60',
      'Copy AUTHOR PROMPT to the author agent and REVIEWER PROMPT to the reviewer agent.',
    ],
    recovery:
      'Before initialization, correct the diagnostic and retry. After initialization, preserve every file and run the exact printed command containing the resolved --dir; never delete partial state.',
    next: [
      'give each thin prompt to its separately assigned agent',
      'each agent reads its complete handoff and runs status',
      'after compaction, reread the handoff and resume the visible wait cycle; ambiguity stops for human review',
    ],
  }),
  init: command({
    purpose: 'Create a new local co-review protocol or import one immutable reviewer round.',
    caller: 'The artifact owner or human coordinator, before either agent begins a new exchange.',
    lifecycleStates: ['absent'],
    mutationBoundary:
      'Creates protocol state under the local mutex; it does not publish an evidence archive.',
    prerequisites: [
      'Run in the Git worktree that contains the authoritative committed artifact.',
      'Choose a caller-owned Git-ignored runtime directory.',
      'Use distinct non-blank owner and reviewer identities and a positive review-turn budget.',
    ],
    usage:
      'npx aitm co-review init --dir <path> --artifact <repo-path> --owner <identity> --reviewer <identity> --max-turns <N> [--archive-dir <tracked-repo-path>] [--import-review <file> --review-of <commit>]',
    arguments: [
      '--dir <path>                 Ignored local protocol directory.',
      '--artifact <repo-path>       Authoritative tracked artifact.',
      '--owner <identity>           Identity allowed to act as owner.',
      '--reviewer <identity>        Distinct identity allowed to act as reviewer.',
      '--max-turns <N>              Positive reviewer-response limit.',
      '--import-review <file>       Existing immutable review; requires --review-of.',
      '--review-of <commit>         Exact commit reviewed by the imported review.',
      '--archive-dir <repo-path>    Optional tracked destination for terminal evidence.',
    ],
    effects: [
      'Creates state.json and events.jsonl under --dir through the protocol mutex.',
      'An imported review is hashed and consumes reviewer turn 1.',
      'An imported review therefore requires --max-turns 2 or greater so the owner can answer it and receive another review.',
    ],
    validations: [
      'Runtime ignore/containment, role separation, budget, Git reachability, artifact blob equality, import pairing, and immutable path separation.',
    ],
    output: 'Prints initialized state, budget, integrity, and the next claim command.',
    exits: '0=initialized/help; 1=protocol or Git refusal; 2=invalid usage.',
    transition: 'Absent -> active owner round 1; imported R1 -> active owner round 2.',
    idempotency: 'An exact configuration/hash retry returns existing state without another event.',
    examples: [
      'npx aitm co-review init --dir .tmp/design-review --artifact docs/design.md --owner owner-agent --reviewer reviewer-agent --max-turns 6',
      'npx aitm co-review init --dir .tmp/1117-review --artifact docs/superpowers/specs/design.md --owner codex --reviewer claude --max-turns 6 --import-review .tmp/1117-review/r1-claude-review.md --review-of abc1234',
    ],
    recovery:
      'If initialization refuses, preserve every input, correct the named invariant, and rerun this exact command. Never delete a surviving lock without human inspection.',
    next: [
      'npx aitm co-review status --dir <path>',
      'npx aitm co-review claim --dir <path> --actor <owner-identity>',
    ],
  }),
  status: command({
    purpose: 'Recover the complete protocol state and verify recorded artifact integrity.',
    caller: 'Owner, reviewer, or human at any time, especially after context loss.',
    lifecycleStates: ['active', 'intervention-required', 'accepted'],
    mutationBoundary:
      'Read-only; inspects protocol integrity and archive completion without writing.',
    prerequisites: ['The --dir protocol must have been initialized.'],
    usage: 'npx aitm co-review status --dir <path> [--json]',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--json                       Emit machine-readable state and next action.',
    ],
    effects: ['Reads state, events, hashes, Git anchors, and lock metadata; writes nothing.'],
    validations: [
      'Schema, revision/budget arithmetic, recorded hashes, artifact/index/branch anchors.',
    ],
    output:
      'Prints lifecycle, actor, role, round, claim, Git ref, budget, integrity, last handoff, and next command.',
    exits:
      '0=integrity verified; 1=not initialized, malformed state, or integrity drift; 2=invalid usage.',
    transition: 'None.',
    idempotency: 'Always read-only and repeatable.',
    examples: [
      'npx aitm co-review status --dir .tmp/design-review',
      'npx aitm co-review status --dir .tmp/design-review --json',
    ],
    recovery:
      'Follow the printed next action. On drift or lock evidence, preserve files and escalate to the human.',
    next: [
      'claim when your configured role is available',
      'wait when the other role owns the turn',
      'stop when accepted',
    ],
  }),
  claim: command({
    purpose: 'Atomically claim the currently available owner or reviewer turn.',
    caller: 'Only the configured identity whose role is displayed as available by status.',
    lifecycleStates: ['active'],
    mutationBoundary: 'Records one claim under the local protocol mutex.',
    prerequisites: [
      'Protocol is active, integrity is clean, and the caller identity maps to the current role.',
    ],
    usage: 'npx aitm co-review claim --dir <path> --actor <identity>',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--actor <identity>           Exact configured owner or reviewer identity.',
    ],
    effects: ['Acquires the mutex and records one claim event with actor/process/host/time.'],
    validations: [
      'Lifecycle, current role, configured identity, availability, integrity, and mutex ownership.',
    ],
    output: 'Prints claimed role/round and the role-specific handoff command.',
    exits:
      '0=claimed or exact idempotent retry; 1=role/state/integrity/lock refusal; 2=invalid usage.',
    transition: 'active available -> active claimed for the same role.',
    idempotency:
      'An exact retry by the recorded claimant returns state without a new revision/event.',
    examples: ['npx aitm co-review claim --dir .tmp/design-review --actor owner-agent'],
    recovery:
      'Wrong actor waits; other claimant stops; lock/drift evidence is preserved and escalated.',
    next: [
      'owner: revise/commit artifact, write response, then handoff',
      'reviewer: review exact owner commit, then handoff',
    ],
  }),
  wait: command({
    purpose: 'Wait briefly and read-only for one configured actor to become claimable.',
    caller: 'Owner or reviewer while the other role has the turn.',
    lifecycleStates: ['active', 'intervention-required', 'accepted'],
    mutationBoundary: 'Read-only polling; never acquires the protocol mutex or writes state.',
    prerequisites: ['Protocol exists and --actor is a configured identity.'],
    usage: 'npx aitm co-review wait --dir <path> --actor <identity> [--timeout <seconds>]',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--actor <identity>           Configured identity waiting for its role.',
      '--timeout <seconds>          0..60 seconds; default 55.',
    ],
    effects: ['Polls status without a mutex and without writing.'],
    validations: ['Actor identity, timeout bounds, state schema, and terminal state.'],
    output: 'Prints available, terminal/intervention, or timeout state and next action.',
    exits:
      '0=available or terminal state observed; 1=protocol/integrity failure; 2=invalid usage; 3=bounded timeout.',
    transition: 'None.',
    idempotency: 'Always read-only and safely repeatable.',
    examples: [
      'npx aitm co-review wait --dir .tmp/design-review --actor reviewer-agent --timeout 55',
    ],
    recovery:
      'A timeout is not failure: report status and repeat another bounded wait if appropriate.',
    next: [
      'claim when available',
      'status after timeout',
      'stop/escalate on accepted/intervention-required',
    ],
  }),
  handoff: command({
    purpose: 'Validate and transfer one completed owner or reviewer turn.',
    caller: 'Only the configured identity holding the claimed current turn.',
    lifecycleStates: ['active'],
    mutationBoundary:
      'Records the handoff under the mutex; reviewer consensus acceptance is durable before archive publication runs after mutex release.',
    prerequisites: [
      'Owner: committed artifact plus immutable response; answers preceding review when present.',
      'Reviewer: immutable review of exact owner commit plus explicit accepted or changes-requested decision.',
    ],
    usage: 'npx aitm co-review handoff --dir <path> --actor <identity> <role-specific-options>',
    arguments: [
      'Owner: --response <file> --artifact <path> --commit <sha> [--answers <review>] --message <text>',
      'Reviewer: --review <file> --review-of <sha> --decision <accepted|changes-requested> [--summary <file>] --message <text>',
    ],
    effects: [
      'Hashes immutable exchange artifacts, appends one handoff event, clears the claim, and transfers/terminates state.',
      'A reviewer handoff consumes exactly one review turn.',
      'Reviewer consensus publishes the configured archive after durable acceptance; a publication failure exits 4 and prints an exact finalize retry.',
    ],
    validations: [
      'Role/claim/round, immutable path/hash separation, finding coverage, exact Git commit/artifact/index/branch, explicit decision, budget, and a summary optional only on the final changes-requested review.',
    ],
    output: 'Prints hashes, decision, used/max/remaining turns, lifecycle, and next command.',
    exits:
      '0=handoff complete; 1=protocol/Git/artifact refusal; 2=invalid or role-inapplicable flags; 4=acceptance durable; archive publication pending.',
    transition:
      'owner -> reviewer; reviewer changes -> owner; reviewer accepted -> accepted; final changes-requested -> active closing owner; closing owner handoff -> intervention-required.',
    idempotency: 'A completed handoff is not replayed; status reveals the already-advanced state.',
    examples: [
      'npx aitm co-review handoff --dir .tmp/design-review --actor owner-agent --response .tmp/design-review/r2-owner-response.md --artifact docs/design.md --commit abc1234 --answers .tmp/design-review/r1-review.md --message "revision ready"',
      'npx aitm co-review handoff --dir .tmp/design-review --actor reviewer-agent --review .tmp/design-review/r3-review.md --review-of abc1234 --decision accepted --message "accepted"',
      'npx aitm co-review handoff --dir .tmp/design-review --actor reviewer-agent --review .tmp/design-review/r6-review.md --review-of abc1234 --decision changes-requested --summary .tmp/design-review/r6-human-summary.md --message "human decision requested"',
    ],
    recovery:
      'Do not edit a handed-off file. Correct only the named unaccepted input; on drift or branch change, stop and escalate. On exhausted budget, follow the displayed next action and complete the closing owner turn before intervention.',
    next: [
      'status',
      'the displayed next-role claim',
      'continue only after intervention-required human approval',
    ],
  }),
  'set-max-turns': command({
    purpose: 'Authenticated adjustment of the absolute reviewer-turn maximum.',
    caller: 'The authenticated GitHub user exercising human budget authority.',
    lifecycleStates: ['active'],
    mutationBoundary:
      'Authenticates first, then records one absolute budget adjustment under the mutex.',
    prerequisites: [
      'The gh CLI is authenticated and the protocol is active.',
      'The requested maximum is a nonnegative integer that preserves any in-progress turn floor.',
    ],
    usage: 'npx aitm co-review set-max-turns --dir <path> --max-turns <N>',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--max-turns <N>              New absolute reviewer-response maximum; may increase or decrease.',
    ],
    effects: [
      'Records authenticated actor, prior/requested/effective maximum, and timestamp.',
      'Preserves the active lifecycle, role, and claim; an exhausted owner budget short-circuits to intervention only on the subsequent owner handoff.',
    ],
    validations: ['GitHub identity, lifecycle, integrity, turn floor, and mutex ownership.'],
    output: 'Prints the effective budget, adjustment provenance, lifecycle, and exact next action.',
    exits: '0=adjusted or exact no-op; 1=identity/state/integrity/lock refusal; 2=invalid usage.',
    transition: 'The active lifecycle, current role, and claim remain unchanged by the adjustment.',
    idempotency: 'An exact effective no-op preserves protocol bytes and emits no event.',
    examples: [
      'npx aitm co-review set-max-turns --dir .tmp/design-review --max-turns 8',
      'npx aitm co-review set-max-turns --dir .tmp/design-review --max-turns 2',
    ],
    recovery:
      'Run gh auth login if identity resolution fails, then rerun the exact printed command. Use status to inspect a closing owner or indefinite pause.',
    next: [
      'status',
      'complete a preserved closing owner turn',
      'continue or finalize after intervention',
    ],
  }),
  supplement: command({
    purpose: 'Register immutable human context while the protocol is paused for intervention.',
    caller: 'The authenticated GitHub user supplying additional review context.',
    lifecycleStates: ['intervention-required'],
    mutationBoundary:
      'Authenticates first, then records one immutable supplement hash under the mutex.',
    prerequisites: [
      'Lifecycle is intervention-required and the supplement is a safe regular file under --dir.',
    ],
    usage: 'npx aitm co-review supplement --dir <path> --file <file>',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--file <file>                Immutable supplement file inside the runtime directory.',
    ],
    effects: [
      'Appends a stable S-N supplement record with authenticated provenance and target round.',
      'Continuation freezes pending supplements; the next reviewer output acknowledges each as [supplement:S-N].',
    ],
    validations: [
      'Identity, intervention lifecycle, containment, file type/hash, uniqueness, integrity, and mutex.',
    ],
    output: 'Prints the supplement id, hash, target round, and intervention status.',
    exits:
      '0=registered or exact idempotent retry; 1=identity/state/file/integrity refusal; 2=invalid usage.',
    transition: 'intervention-required remains intervention-required.',
    idempotency: 'The same path and bytes return the existing registration without another event.',
    examples: [
      'npx aitm co-review supplement --dir .tmp/design-review --file .tmp/design-review/human-context.md',
    ],
    recovery:
      'Preserve registered bytes. Correct only an unaccepted file, authenticate with gh auth login when required, and rerun.',
    next: ['register another supplement', 'continue', 'finalize --good-enough', 'make no mutation'],
  }),
  continue: command({
    purpose: 'Authenticated continuation after mandatory human interception.',
    caller: 'The authenticated GitHub user exercising human continuation authority.',
    lifecycleStates: ['intervention-required'],
    mutationBoundary:
      'Authenticates first, then records continuation and freezes supplements under the mutex.',
    prerequisites: [
      'Lifecycle is intervention-required and the last review/summary remain intact.',
    ],
    usage:
      'npx aitm co-review continue --dir <path> [--max-turns <N> | --additional-turns <N>] [--focus <file>]',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--max-turns <N>              New absolute maximum; bare continuation authorizes the minimum required by the resumed role.',
      '--additional-turns <N>       Legacy positive additive form; mutually exclusive with --max-turns.',
      '--approved-by <identity>     Deprecated and ignored; authenticated GitHub login is authoritative.',
      '--focus <file>               Optional immutable human refocus instructions.',
    ],
    effects: [
      'Derives the resumed role from the last handoff: owner resumes reviewer; reviewer resumes owner.',
      'Authorizes the resumed role minimum, freezes pending supplements, hashes optional focus, and returns that role available.',
    ],
    validations: [
      'Authenticated identity, intervention lifecycle, budget form, integrity, focus containment/separation, supplements, and mutex.',
    ],
    output:
      'Prints approval/refocus provenance, cumulative budget, resumed role, and its claim command.',
    exits: '0=continued; 1=state/integrity/lock refusal; 2=invalid usage.',
    transition:
      'intervention after a closing owner -> active reviewer available; legacy intervention after an exhausted reviewer -> active owner available; accepted cannot continue.',
    idempotency:
      'Not replayable after success because the protocol is no longer intervention-required.',
    examples: [
      'npx aitm co-review continue --dir .tmp/design-review',
      'npx aitm co-review continue --dir .tmp/design-review --max-turns 8 --focus .tmp/design-review/refocus.md',
      'npx aitm co-review continue --dir .tmp/design-review --additional-turns 2',
    ],
    recovery:
      'If approval or focus is wrong, correct it before success. After success, do not rerun; use status.',
    next: [
      'claim with the displayed resumed-role actor command',
      'npx aitm co-review status --dir <path>',
    ],
  }),
  finalize: command({
    purpose: 'Publish terminal evidence for accepted consensus or authenticated human good enough.',
    caller:
      'Any operator retrying accepted publication, or the authenticated human choosing good enough.',
    lifecycleStates: ['intervention-required', 'accepted'],
    mutationBoundary:
      'Accepted-session retries never mutate protocol; good enough prepares first, records terminal acceptance under the mutex, then publishes after mutex release.',
    prerequisites: [
      'Accepted consensus, or author-completed intervention with a two-sided closing evidence pair for --good-enough.',
      'A configured archive destination or explicit --archive-dir tracked repository path.',
    ],
    usage:
      'npx aitm co-review finalize --dir <path> [--good-enough] [--archive-dir <tracked-repo-path>] [--json]',
    arguments: [
      '--dir <path>                 Existing protocol directory.',
      '--good-enough                Authenticated human terminal acceptance from eligible intervention.',
      '--archive-dir <repo-path>    Required for legacy/unconfigured sessions; must stay inside the repository.',
      '--json                       Emit state and publication result as JSON.',
    ],
    effects: [
      'Validates and publishes deterministic exact-byte evidence without staging or committing it.',
      'Good enough records basis, authenticated actor, timestamp, and one human-good-enough event before publication.',
    ],
    validations: [
      'Lifecycle, expected revision, two-sided evidence, identity, destination containment, immutable source bytes, and archive conflicts.',
    ],
    output:
      'Prints every produced repository-relative path and host repository governance guidance.',
    exits:
      '0=archive complete or identical; 1=protocol/evidence/destination/conflict refusal; 2=invalid usage; 4=acceptance durable; archive publication pending.',
    transition: 'intervention-required --good-enough -> accepted; accepted remains terminal.',
    idempotency:
      'An identical archive retry succeeds without rewriting; conflicting output is refused.',
    examples: [
      'npx aitm co-review finalize --dir .tmp/design-review',
      'npx aitm co-review finalize --dir .tmp/legacy-review --archive-dir docs/reviews/legacy',
      'npx aitm co-review finalize --dir .tmp/design-review --good-enough',
    ],
    recovery:
      'Exit 4 means acceptance is durable; preserve state and run the exact printed finalize retry. Never retry the terminal handoff.',
    next: [
      'verify exact bytes',
      'stage and commit through host repository governance',
      'stop; accepted is terminal',
    ],
  }),
});

const HELP_TOKENS = new Set(['help', '--help', '-h', '?']);

export function helpRequest(argv = []) {
  if (argv.length === 1 && HELP_TOKENS.has(argv[0])) return { requested: true, command: null };
  if (argv.length === 2 && argv[0] === 'help' && COMMANDS[argv[1]]) {
    return { requested: true, command: argv[1] };
  }
  if (argv.length === 2 && COMMANDS[argv[0]] && HELP_TOKENS.has(argv[1])) {
    return { requested: true, command: argv[0] };
  }
  return { requested: false };
}

function list(label, values) {
  return [`${label}:`, ...values.map((value) => `  - ${value}`)];
}

function renderCommandHelp(name) {
  const entry = COMMANDS[name];
  if (!entry) return `co-review: unknown help command "${name}"\n`;
  return [
    `co-review ${name}`,
    '',
    `Purpose: ${entry.purpose}`,
    `Authorized caller: ${entry.caller}`,
    `Lifecycle states: ${entry.lifecycleStates.join(', ')}`,
    `Mutation boundary: ${entry.mutationBoundary}`,
    ...list('Prerequisites', entry.prerequisites),
    `Usage: ${entry.usage}`,
    ...list('Arguments', entry.arguments),
    ...list('Effects', entry.effects),
    ...list('Validations', entry.validations),
    `Output: ${entry.output}`,
    `Exit codes: ${entry.exits}`,
    `State transition: ${entry.transition}`,
    `Idempotency: ${entry.idempotency}`,
    ...list('Examples', entry.examples),
    `Failure recovery: ${entry.recovery}`,
    ...list('Next commands', entry.next),
    '',
    'Help is read-only: it performs no repository discovery, lock acquisition, network access, or write.',
    '',
  ].join('\n');
}

function renderTopHelp() {
  const commandNames = Object.keys(COMMANDS);
  const commandTable = Object.entries(COMMANDS)
    .map(
      ([name, entry]) => `  ${name}
    Authorized caller: ${entry.caller}
    Lifecycle states: ${entry.lifecycleStates.join(', ')}
    Mutation boundary: ${entry.mutationBoundary}
    Usage: ${entry.usage}
    Purpose: ${entry.purpose}`
    )
    .join('\n');
  return `co-review — model-agnostic artifact owner / external reviewer handshake

Purpose: Coordinate immutable owner/reviewer artifact rounds through explicit acceptance or human interception.
Usage: npx aitm co-review <${commandNames.join('|')}> [command options]
Audience: Artifact owners, external reviewers, and the human continuation authority.
Arguments: Run npx aitm co-review help <command> for exact required and optional flags.
Preconditions: Normal commands require a Git worktree, tracked artifact, and an ignored --dir selected by the caller or derived by start; help requires nothing.
Effects: Protocol mutations stay under --dir; terminal archive publication writes exact bytes only to a validated tracked repository destination. Help, status, and wait are read-only.
Output: Recovery instructions, validated state, immutable hashes, budget arithmetic, and the exact next action.
Exit codes: 0=success/help; 1=runtime/integrity/protocol refusal; 2=invalid usage; 3=bounded wait timeout; 4=acceptance durable; archive publication pending.
Examples: npx aitm co-review --help; npx aitm co-review status --dir .tmp/design-review
Related: npx aitm help; npx aitm verify-develop

WHAT
  Coordinates immutable owner responses and reviewer decisions around one authoritative committed artifact.

WHY
  Chat context is transient. Atomic turns, hashes, exact Git anchors, explicit decisions, and an event trail make every round recoverable and auditable.

WHO
  owner: exclusively edits/commits the artifact and answers every finding.
  reviewer: reads the exact handoff and writes an immutable accepted or changes-requested review.
  human: authenticates through gh before budget adjustment, supplements, continuation/refocus, or good-enough acceptance.
  If authentication fails, run gh auth login and rerun the exact recovery command.

WHEN
  start before review; init remains the low-level primitive; status after context loss; claim before work; wait while the other role acts; handoff after immutable artifacts are complete; set-max-turns only during active state; supplement and continue/finalize only at intervention; finalize after accepted publication failure; stop forever after accepted.

WHERE
  The authoritative artifact is a tracked repository path. --dir is a caller-selected or guided-start-derived Git-ignored local directory containing state.json, events.jsonl, generated handoffs, round artifacts, summaries, optional refocus files, and a short-lived .co-review-lock/.

HOW
  Every mutation validates, acquires a non-stealing directory mutex, revalidates, hashes accepted artifacts with SHA-256, appends one event, and atomically replaces state. The owner handoff proves exact commit/artifact/index equality. The reviewer handoff proves no owner-side Git drift.

LIFECYCLE
  active owner -> active reviewer -> active owner ... -> accepted
                                     final changes-requested -> active closing owner
                                     closing owner handoff -> intervention-required
                                     human continue -> active role implied by the last handoff
                                     human finalize --good-enough -> accepted
  accepted is terminal and wins over budget exhaustion on the last allowed review.

COMMANDS
${commandTable}
  Run: npx aitm co-review help <command>

OPTION GLOSSARY
  --dir local ignored protocol directory; --artifact authoritative tracked file;
  --owner/--reviewer configured identities; --actor exact acting identity;
  --max-turns total/absolute reviewer responses, including imported R1;
  --wait-cycles separately observed waits per generated-handoff episode;
  --wait-interval bounded seconds for each generated-handoff wait;
  --archive-dir validated tracked repository destination for terminal evidence;
  --decision accepted|changes-requested; --summary optional only on a final changes-requested review;
  --file immutable intervention supplement; --additional-turns legacy additive budget;
  --approved-by deprecated/ignored; authenticated gh login is authoritative;
  --focus optional immutable human refocus file; --good-enough terminal human acceptance;
  --timeout bounded 0..60 seconds; --json machine-readable status/finalization.

ARTIFACT FORMAT
  Response, review, supplement, and archive inputs are Markdown expected to satisfy host repository governance.
  Reviewer findings: [finding:F-001]
  Owner responses:    [finding:F-001] [disposition:accepted]
  Dispositions: accepted | accepted-with-modification | rejected | deferred
  Rejected also uses [evidence:<repo-path-or-command>].
  Deferred also uses [follow-up:#N] and [safe-boundary:<text>].
  A reviewer acknowledges every frozen supplement as [supplement:S-001].
  A handed-off review, response, summary, or focus file is immutable.
  Terminal archives preserve exact bytes and refuse missing, extra, changed, or conflicting evidence.

EXIT CODES
  0 success or help; 1 runtime/integrity/protocol refusal; 2 invalid usage; 3 bounded wait timeout; 4 acceptance durable; archive publication pending.

FRESH EXAMPLE
  npx aitm co-review init --dir .tmp/design-review --artifact docs/design.md --owner owner-agent --reviewer reviewer-agent --max-turns 6 --archive-dir docs/reviews/design
  npx aitm co-review claim --dir .tmp/design-review --actor owner-agent
  # Owner commits docs/design.md and writes .tmp/design-review/r1-owner-response.md
  npx aitm co-review handoff --dir <path> --actor <owner-identity> --response <response-file> --artifact <artifact-path> --commit <sha> --message <text>
  npx aitm co-review claim --dir <path> --actor <reviewer-identity>
  # Reviewer writes an immutable review of that exact SHA
  npx aitm co-review handoff --dir <path> --actor <reviewer-identity> --review <review-file> --review-of <sha> --decision <accepted|changes-requested> --message <text>
  # On changes-requested, the owner claims, revises, answers the exact review with --answers, and repeats.

IMPORTED R1 EXAMPLE
  npx aitm co-review init --dir .tmp/1117-review --artifact docs/design.md --owner codex --reviewer claude --max-turns 6 --import-review .tmp/1117-review/r1-claude-review.md --review-of <sha>
  The imported review consumes turn 1; used=1, max=6, remaining=5.
  # If the last allowed review requests changes, summary is optional; the owner must still claim, answer, commit, and hand off once before intervention.
  npx aitm co-review set-max-turns --dir <path> --max-turns <N>
  npx aitm co-review supplement --dir <path> --file <supplement-file>
  npx aitm co-review continue --dir <path> [--max-turns <N> | --additional-turns <N>] [--focus <file>]
  npx aitm co-review continue --dir <path> --additional-turns <N>
  npx aitm co-review finalize --dir <path> --good-enough [--archive-dir <tracked-repo-path>]
  # Human authority is the authenticated gh login. Bare continuation authorizes the minimum required by the role implied by the last handoff.

ACCEPTED PUBLICATION RECOVERY
  Ordinary reviewer consensus publishes automatically when --archive-dir was configured at init.
  Exit 4 means the acceptance transition is durable but archive publication is pending.
  Run the exact printed finalize retry; legacy accepted sessions supply --archive-dir explicitly.
  Verify every produced path and commit through host repository governance; co-review never stages or commits.

COMMON REFUSALS
  Wrong role/claim, malformed state, missing/drifted immutable artifact, dirty index/artifact, branch/commit drift, incomplete dispositions, implicit decision, a summary before the final changes-requested review, or surviving lock. Every refusal leaves the attempted transition unapplied and prints a recovery action.

CONTEXT-RESET CHECKLIST
  1. Run: npx aitm co-review status --dir <path>
  2. Confirm the configured artifact, exact commit, role identity, lifecycle, and budget.
  3. If available, claim with the displayed actor command.
  4. If claimed by you, complete only your role's immutable artifacts and handoff.
  5. If intervention-required, stop and ask the human; do not invent approval.
  6. If accepted with pending publication, run the exact finalize retry; otherwise stop.
  7. If locked or drifted, preserve files and escalate with the printed diagnostics.
  8. Treat generated archive files as exact bytes and use host repository governance for staging and commit.

Help is safe before init and performs no repository discovery, lock acquisition, network access, or write.
`;
}

export function renderHelp(commandName = null) {
  return commandName ? renderCommandHelp(commandName) : renderTopHelp();
}
